### ISSUE TITLE
I don't think we need nodemon anymore...

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/p4nth3rb0t-mainframe#116]

**Comment by ricardodevries** [comment]
What are you using instead? I am currently using [ts-node-dev](https://www.npmjs.com/package/ts-node-dev) for p4nth3rb0t.

**Comment by whitep4nth3r** [comment]
I’m currently using nodemon, but I believe we can remove it in favour of
ts-node.

**Comment by ricardodevries** [comment]
Please take a look at https://stackoverflow.com/a/70933036 and let me know the next step regarding nodemon.

**Comment by whitep4nth3r** [comment]
Go with node-dev plus ts-node because I don't like the idea of ts-node-dev being unreliable. I have enough problems LOL.
