### ISSUE TITLE
node-20 branch issues

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/p4nth3rb0t-mainframe#144]
## 1. twitchUtils/getCurrentChatters 

Returns unauthorized (when attempting to !gift)

- unsure if this is a result of the called functions in order, or whether I just need to locally reauth

https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/tree/node-20

**Comment by whitep4nth3r** [comment]
cc @ricardodevries

**Comment by ricardodevries** [comment]
My latest changes have been merged in your branch: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/tree/node-20

Please check if any bugs occur. I ran it for two days without any error but lets see if you get any issues.

**Comment by ricardodevries** [comment]
To complicate things even more: When there are no issues, please make a PR of your branch so we can fix merge conflicts. God I love Git (not).
