### ISSUE TITLE
Response is never sent if an uncaught exception occurs in an express route

### ISSUE THREAD

**Issue by soryy708** [whitep4nth3r/p4nth3rb0t-mainframe#19]
This can be mitigated by implementing an error-handling middleware.
https://expressjs.com/en/guide/error-handling.html

**Comment by MadhouseSteve** [comment]
Thanks for the feedback. You're welcome to submit a PR which will be reviewed in a future stream.

**Comment by soryy708** [comment]
@MadhouseSteve PR has been created.
@whitep4nth3r On stream you said you don't want error handling middleware, and I see that you closed the issue.
