### ISSUE TITLE
The Typed Actions / Events / Packets "Plan"

### ISSUE THREAD

**Issue by negue** [whitep4nth3r/p4nth3rb0t-mainframe#39]
Currently we have the enums / types / actions in two places (maybe even more?) - one is the mainframe, one is the pantherlabs

To remove a lot of duplicated code / types / headaches I think it would be the best to combine / and refactor the current types - so that at the end the mainframe and labs types are the same not "alike"  (in labs, we have the events from Websocket and the actions and their types ... and headaches)

I think we can all agree on that part ^ 

---

But,

where do we put those types / contracts ?

We have 3 ways to do it (if someone has another idea please tell me)

1. Put the types / contracts into a public repo (my idea would be in pantherlabs), which then could be imported into this repo using a git submodule
   -> PRO: this would give us one place for the types
   -> CON: creating new features would have to be done in the types first - then pushed to main branch of labs - and then you can do the front- / backend parts

2. Extract the types to its own npm package and use it then on both front- and backend
    -> CON: same as 1) just types have to pushed to npm, which is one more step to publish to NPM

3. Use a monorepo for front- and backend
    -> PRO: every new feature can be done in place / repo / pr
    -> CON: this repo would have to be public ... or both would have to be private

Ideally I'd choose 3) but the CONs have to be decided first ^^  

on my 2nd choice I'd say we go the "1"st Route for now?

**Comment by whitep4nth3r** [comment]
Personally, I think I like option 2 the best. Might be easier than submodules, and also it mirrors the way I did websocket validation in p4nth3rball with Ryan's validation package.

**Comment by SociableSteve** [comment]
Common stuff should probably be moved to its own repo, and included as an npm package. There are definitely pros and cons to each option.

Is there an option of publishing an SDK as part of the mainframe build, which any consumers can then use?

Going with option 2, you can include an NPM package from a git repo, rather than a full blown NPM package in the central registry. If the types were in a public github repo that might also work for this purpose. The mainframe isn't really designed for public consumption after all.

How much of an overhead/headache is there in the current setup? Is this a problem which doesn't need solving yet? I can say I've not experienced much issue, but I've not done the lions share of the work, so maybe there is an issue here that I haven't personally been hit by.

**Comment by whitep4nth3r** [comment]
I think the issues started arising when I was working on the giveaway bot, and copying and pasting the same patterns from the alerts/chat messages created more of a hindrance than a help.

@negue saw the issue and then worked on a PR into main - but seeing as I had already made such progress on the giveaway-fun branch, it would have been horrible to merge the PR into main, and then main into giveaway-fun.

I mean, that's still an option - and it'll be fixed - ish.

Maybe we just do that?

**Comment by SociableSteve** [comment]
Sounds like there is a real problem then. My preferred option is to have a @whitep4nth3r/types (or similarly named) repo and put the typings into that, then include those as an npm dependency, either directly from GH or as an NPM package, essentially option 2. This follows similar patterns from other projects where there's not a specific SDK with bundled types.

**Comment by negue** [comment]
Going with Option 2 and a github repo instead of npm might be a good idea :) 

> I mean, that's still an option - and it'll be fixed - ish.

> Maybe we just do that?

Let me try the types repo (could you create that?) first, if that doesn't work then we still have the fallback of the PR

**Comment by whitep4nth3r** [comment]
https://github.com/whitep4nth3r/p4nth3rb0t-types

**Comment by whitep4nth3r** [comment]
Closed with https://www.npmjs.com/package/@whitep4nth3r/p4nth3rb0t-types
