### ISSUE TITLE
Add support for User Access Tokens

### ISSUE THREAD

**Issue by jwalter** [whitep4nth3r/p4nth3rb0t-mainframe#81]
User access tokens are needed for certain API:s, for example the /chatters API that was "recently" removed from tmi.

Rough plan:

## Authorization code grant flow
This flow is meant for apps that use a server, can securely store a client secret, and can make server-to-server requests to the Twitch API.
To get a user access token using the authorization code grant flow, your app must:
 * Get the user to authorize your app
 * Use the authorization code to get a token.

### Handling the auth code
Auth code will be stored in mongodb. When none is found, or access token can not be acquired with the found code:
* Generate a random uuid to use as "state"
* Store the "state" in mongodb
* Show message to broadcaster about auth needed
* The "state" value should be included in the url shown to broadcaster
* Initiate the auth code dance with Twitch
* Validate the "state" property in the response
* Validate that the user token matches the broadcaster by calling the /validate endpoint?
(https://dev.twitch.tv/docs/authentication/validate-tokens/#how-to-validate-a-token)

### Getting a user access token
User access token is cached in mongodb.
* Get auth code from mongodb and exchange it for user access token

### Refreshing token
Refresh token is cached in mongodb. When token expires, Twitch responds with 401.
Do _not_ try to predict the expiry, just handle it when 401 is returned.

**Comment by jwalter** [comment]
I've started working on this. Got the basic flow working but the code is a hot mess and token refresh needs to be implemented.

**Comment by whitep4nth3r** [comment]
And no strim? 🫠

Seriously, thank you!

**Comment by whitep4nth3r** [comment]
How's the fix for megatimeout going? When that's done I think we can close this?

**Comment by jwalter** [comment]
What was it we wanted to fix? The command is working now, as long as the broadcaster clears the auth token manually once

**Comment by whitep4nth3r** [comment]
Oh I didn't realise I had to now clear it manually. 

Now... where's my MongoDB login for production 😂

**Comment by jwalter** [comment]
Fixed in #82
