### ISSUE TITLE
Consider using Twitch's shoutout

### ISSUE THREAD

**Issue by ricardodevries** [whitep4nth3r/p4nth3rb0t-mainframe#91]
Sends a Shoutout to the specified broadcaster. Typically, you send Shoutouts when you or one of your moderators notice another broadcaster in your chat, the other broadcaster is coming up in conversation, or after they raid your broadcast: https://dev.twitch.tv/docs/api/reference/#send-a-shoutout

![image](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/7f7e5300-7662-45bf-9bd7-144b63d5f4ca)
![image](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/8568b476-68ca-4712-a91d-c2d8b2333184)
![image](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/f0e1fa47-d920-429e-b791-71819cdca121)
![image](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/79a2307d-f432-4f1a-ba27-c1fb481cf8a4)

**Authorization**
Requires a [user access token](https://dev.twitch.tv/docs/authentication#user-access-tokens) that includes the `moderator:manage:shoutouts` scope. This scope needs to be added to:

https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/blob/f5e31d56ee36d9b99d581a871a2520de2046104e/src/classes/AccessToken.ts#L42

**URL**
POST `https://api.twitch.tv/helix/chat/shoutouts`

**Request Query Parameters**
Parameter | Type | Required? | Description
-- | -- | -- | --
from_broadcaster_id | String | Yes | The ID of the broadcaster that’s sending the Shoutout.
to_broadcaster_id | String | Yes | The ID of the broadcaster that’s receiving the Shoutout.
moderator_id | String | Yes | The ID of the broadcaster or a user that is one of the broadcaster’s moderators. This ID must match the user ID in the access token.

**Comment by ricardodevries** [comment]
@jwalter @whitep4nth3r: I tried implementing the shoutout feature and that works on the following conditions:

- The bot accessed the user token, the API call is:
```
https://api.twitch.tv/helix/chat/shoutouts?from_broadcaster_id=${config.broadcaster.user_id}&to_broadcaster_id=${toBroadcasterId}&moderator_id=${config.bot.user_id}
```
- In the announce url we need to change the moderator id to config.bot.user_id:
https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/blob/2672c473d145e0d3bc4737feb024ce40b924c192/src/utils/twitchUtils.ts#L122
to
```
https://api.twitch.tv/helix/chat/announcements?broadcaster_id=${config.broadcaster.user_id}&moderator_id=${config.bot.user_id}
```

I believe then you can do the user access token via the bot instead of your own user. I did not recieve any error when doing the access token via the bot, yet.

![Capture](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/725c7413-be4c-41dd-bf9f-264c6a29ad8f)
![test1](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/acdd6eb5-9c64-4096-ae47-ab3203241feb)

The full code:

```typescript
export const shoutOut = async (toBroadcasterId: string): Promise<any> => {
  const url = `https://api.twitch.tv/helix/chat/shoutouts?from_broadcaster_id=${config.broadcaster.user_id}&to_broadcaster_id=${toBroadcasterId}&moderator_id=${config.bot.user_id}`;
  const response = await doPost(url, null);

  if (response) {
    console.log(`Shoutout to ${toBroadcasterId}`);
  }
};
```

**Comment by jwalter** [comment]
If you use an auth code issued by bot account, then I believe you are correct. We would need to change the other methods in twitchUtils that uses a moderator_id parameter (getCurrentChatters and timeoutUserFor60Seconds) since they send config.broadcaster.user_id as value, in order to fully support a bot issued auth code+token. The good thing is that you _can_ still use a broadcaster issued token by simply using the broadcasters id as bot.user_id in the config.
