### ISSUE TITLE
Announce with p4nth3rb0t instead of broadcaster

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/p4nth3rb0t-mainframe#96]
Currently we are announcing using the broadcaster account.

It would be preferable to announce using the `config.bot.user_id`, but this requires some access token configuration.

**Comment by ricardodevries** [comment]
This is what I suggested in #95. Please take a look at the comment from @jwalter in https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/95#issue-1870225860 (bullet 2).

If we are going to follow his suggestion we need to adjust some files: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/95#issuecomment-1696148734 and then we also need to revert https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/95/commits/148b5b0415392607e2e235d9827f9a2f4fc72399 in the PR.

Then authentication with user access tokens need to be done with the bot account:

**Comment by whitep4nth3r** [comment]
Gotcha. I completely misunderstood that [this comment](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/95#issuecomment-1696194373) meant that I would be announcing with my account and not the bot.

**Comment by ricardodevries** [comment]
@whitep4nth3r I'll add the necessary changes in #95 to completely support the bot.

**Comment by whitep4nth3r** [comment]
Thank you!
