### ISSUE TITLE
Consider creating an automated release tagging system

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/p4nth3rb0t-mainframe#97]
This is primarily so that we can track releases in the Sentry SDK by name.

Not sure of the best solution here.

**Comment by whitep4nth3r** [comment]
@jwalter @ricardodevries please advise :D

**Comment by whitep4nth3r** [comment]
This should be completed before we merge any other features.

**Comment by ricardodevries** [comment]
> @jwalter @ricardodevries please advise :D

@whitep4nth3r: Take a look at #102 to see if that is what you need. I looked and heroku doesn't care about versioning. If your application is launched with npm start, you can simply use: `process.env.npm_package_version` and apparently that is used on heroku:
![image](https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/assets/78354174/84318557-79ed-4e3e-9ff2-91ed13806a01)
